#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: hf-podcast
  description: Hyperledger Foundation Podcast
  homepage: https://hyperledger.org/
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: true
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
